replaced old TR() with updated TR() due to...
Error: incompatible types, expecting a numeric vector
9 stop(structure(list(message = "incompatible types, expecting a numeric vector",
    call = NULL, cppstack = NULL), .Names = c("message", "call",
"cppstack"), class = c("Rcpp::exception", "C++Error", "error",
"condition")))
8 mutate_impl(.data, dots)
7 mutate_.tbl_df(.data, .dots = lazyeval::lazy_dots(...))
6 mutate_(.data, .dots = lazyeval::lazy_dots(...))
5 mutate(d_b, score = ifelse(rgn_id %in% unpopulated$rgn_id, NA,
    score)) at functions.R#989
4 TR(layers, year_max = 2011) at <text>#1
3 eval(expr, envir, enclos)
2 eval(parse(text = goals_X$preindex_function[i]), envir = conf$functions)
1 CalculateAll(conf, layers, debug = F)